sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets/img"
    values:
      image: true

title: Kwan
name: Kwan
description: 身为代码狗，技术菜就是罪恶，没错就是我
url: https://github.com/yizhishi

github: https://github.com/yizhishi
rss: true
avatar: 

show_excerpt: true


email: mailto:283620911@qq.com


plugins:
  - rouge
  - kramdown
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

exclude:
  - script
  - docs
  - vendor
  - Gemfile
  - Gemfile.lock
